// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SAO": actions Resource Client
//
// Command:
// $ go generate

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// SubmitEntryActionsPath computes a request path to the submitEntry action of actions.
func SubmitEntryActionsPath() string {

	return fmt.Sprintf("/sao/v1/submit-entry")
}

// Orchestrates the resource creation related to a entry submit process (Entry, Token, Result and Score).
func (c *Client) SubmitEntryActions(ctx context.Context, path string, payload *EntryPayload, contentType string) (*http.Response, error) {
	req, err := c.NewSubmitEntryActionsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSubmitEntryActionsRequest create the request corresponding to the submitEntry action endpoint of the actions resource.
func (c *Client) NewSubmitEntryActionsRequest(ctx context.Context, path string, payload *EntryPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// SubmitEntryDraftActionsPath computes a request path to the submitEntryDraft action of actions.
func SubmitEntryDraftActionsPath() string {

	return fmt.Sprintf("/sao/v1/submit-draft")
}

// Orchestrates the resource creation related to a entry draft submit process (Draft and Result).
func (c *Client) SubmitEntryDraftActions(ctx context.Context, path string, payload *EntryPayload, contentType string) (*http.Response, error) {
	req, err := c.NewSubmitEntryDraftActionsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSubmitEntryDraftActionsRequest create the request corresponding to the submitEntryDraft action endpoint of the actions resource.
func (c *Client) NewSubmitEntryDraftActionsRequest(ctx context.Context, path string, payload *EntryPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// SummarizeScoreActionsPath computes a request path to the summarizeScore action of actions.
func SummarizeScoreActionsPath() string {

	return fmt.Sprintf("/sao/v1/summarize-score")
}

// List scores and its total grouped and filter by contest, task or user
func (c *Client) SummarizeScoreActions(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewSummarizeScoreActionsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSummarizeScoreActionsRequest create the request corresponding to the summarizeScore action endpoint of the actions resource.
func (c *Client) NewSummarizeScoreActionsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
