[[constraint]]
  name = "github.com/goadesign/goa"
  version = "1.4.0"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "master"

[[constraint]]
  name = "github.com/ufoscout/go-up"
  version = "v0.5.0"

[prune]
  go-tests = true
  unused-packages = true
