[[constraint]]
  name = "github.com/goadesign/goa"
  version = "1.4.1"

[[constraint]]
  name = "github.com/ufoscout/go-up"
  version = "0.5.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.0.2"

#[[constraint]]
#  name = "github.com/dghubble/sling"
#  version = "1.1.0"

[[constraint]]
  name = "github.com/hashicorp/go-retryablehttp"
  revision = "master"

[prune]
  go-tests = true
  unused-packages = true
