version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cms-orbits/cms-sao

    steps:
    - checkout
    - run: dep ensure -v
    - run: go test -v ./...
    - run: go build -v
